issues:
  exclude-rules:
    - path: (.+)_test.go
      linters:
        - exhaustruct
        - err113
        - testpackage
        - funlen
        - varnamelen
        - dupl
linters:
  enable-all: true
  disable:
    - lll
    - depguard
    - wrapcheck
    - wsl
    - nlreturn
    - interfacebloat
    - ireturn
