with-expecter: true
resolve-type-alias: false
issue-845-fix: true
packages:
  github.com/xabsvoid/eis/internal/app/domain/repository:
    config:
      dir: "internal/pkg/mock"
      outpkg: "mock"
      filename: "{{.InterfaceName | snakecase}}.go"
    interfaces:
      Repository:
